---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars.yml


  tasks:

  - name: software
    include_tasks: tasks/software/software.yml

  - name: config zsh
    include_tasks: tasks/config/zsh.yml

  - name: config nvim
    include_tasks: tasks/config/nvim.yml