- name: downloading lazydocker install script
  get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: "{{ temp_git_folder }}/lazydocker.sh"
    mode: 0755

- name: running install script
  become: true
  become_user: "{{ my_user }}"
  script:
    cmd: "{{ temp_git_folder }}/lazydocker.sh"