- name: software | installing packages
  package:
    name: 
      - htop
      - tmux
      - zsh
      - neovim
      - openssh
      - putty
      - fzf
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
      - code
      - sublime-text

- name: software | fedora-specific
  package:
    name:
      - dnf-plugins-core
  when: ansible_facts["distribution"] == "Fedora"
