- name: software | installing packages
  package:
    name: 
      - htop
      - tmux
      - zsh
      - neovim
      - openssh
      - putty

- name: software | fedora-specific
  package:
    name:
      - dnf-plugins-core
  when: ansible_facts["distribution"] == "Fedora"
