- name: software
  block:
    - name: preflight
      include_tasks: preflight.yml

    - name: packages
      include_tasks: packages.yml

    - name: flatpaks
      include_tasks: flatpaks.yml

    - name: lazydocker
      include_tasks: lazydocker.yml

    - name: nvm
      include_tasks: nvm.yml
    
    - name: cleanup
      file:
        path: "{{ temp_git_folder }}"
        state: absent
