- name: software |
  block:
    - name: preflight | Create temporary folder
      file:
        path: "{{ temp_git_folder }}"
        state: directory
        mode: 0755

    - name: packages
      include_tasks: packages.yml

    - name: lazydocker
      include_tasks: lazydocker.yml

    - name: docker
      include_tasks: docker.yml
    
    - name: cleanup | Remove temporary folder
      file:
        path: "{{ temp_git_folder }}"
        state: absent
